#!/usr/bin/env bash

WEB_USER=$GNOME_FTP_USER
WEB_HOST=master.gnome.org
WEB_DOAP_PATH=/ftp/pub/GNOME/sources/banshee/

#OSX_USER=Build
#OSX_HOST=164.99.121.141
#OSX_BUILD_DIR='$HOME'/banshee-build/build/osx
#OSX_GIT=/usr/local/git/bin/git
