#!/usr/bin/env perl

open (IN, '../NEWS');
$news = '';
while (my $line = readline(IN)) {
    $news .= $line;
}
close (IN);

# Parse various bits out of NEWS
$news =~ m/Banshee ([\S]+) - ([^\n]+)$/ms;
$version = $1;
$release_date = $2;

$version =~ m/(\d+\.\d+)\./;
$series = $1;

$news =~ m/[=]+\n\n(.+)New Features[^:]*:(.+)Enhancements/ms;
$desc = $1;

$features = $2;
$features =~ s!\*([^\n]+)\n([^\*]+)!<h4>$1</h4>\n<p>$2</p>\n!g;

$news =~ m/Enhancements:(.+)Notable Bugs/ms;
$enhancements = $1;
$enhancements =~ s/ \*/ <li>/g;

$news =~ m/Notable Bugs Fixed \(([^\)]+)\):\n([^=]+)\n\n/ms;
$bugs_since = $1;
$bugs = $2;
$bugs =~ s! bgo#(\d+): ([^\n]+)\n! <a href="http://bugzilla.gnome.org/show_bug.cgi?id=$1">bgo#$1</a>: $2\n!g;
$bugs =~ s/ \*/ <li>/g;

$news =~ m/there would be no release!(.+)The following people.+much more limited.(.+)/ms;
$contributors = $1;
$translators = $2;

$html = <<END;
<ul>
	<li><strong>Release Date:</strong> $release_date</li>
	<li><strong>Source Tarball:</strong> <a href="http://ftp.gnome.org/pub/GNOME/sources/banshee/$series/banshee-$version.tar.xz">banshee-$version.tar.xz</a></li>
	<li><strong>Release Information:</strong>
<a href="http://ftp.gnome.org/pub/GNOME/sources/banshee/$series/banshee-$version.news">NEWS</a>,
<a href="http://ftp.gnome.org/pub/GNOME/sources/banshee/$series/banshee-$version.sha256sum">sha256sum</a></li>
</ul>
<p style="margin-left: 1.5em"><a href="/download"><img title="Download the latest Banshee!" src="/theme/css/images/download-button.png" alt="Download Now" /></a></p>

<p>
    $desc
</p>

$features
<h3>Other Enhancements</h3>
<ul>
    $enhancements
</ul>

<h3>Notable Bug Fixes ($bugs_since!)</h3>
<ul>
    $bugs
</ul>
<br>
<h4>Banshee has a lot more to offer! Check out the previous major release notes...</h4>
<ul>
	<li><a href="/download/archives/2.2.0">Read about features added in Banshee 2.2.0</a></li>
	<li><a href="/download/archives/2.0.0">Read about features added in Banshee 2.0.0</a></li>
	<li><a href="/download/archives/1.8.0">Read about features added in Banshee 1.8.0</a></li>
	<li><a href="/download/archives/1.6.0">Read about features added in Banshee 1.6.0</a></li>
	<li><a href="/download/archives/1.4.0">Read about features added in Banshee 1.4.0</a></li>
</ul>
<h3>Dependencies</h3>
<ul>
	<li>Mono 2.4.3 (.NET 2.0 Profile / gmcs)</li>
	<li>SQlite 3.4</li>
	<li>Gtk# 2.12.10</li>
	<li>GStreamer 0.10.26</li>
	<li>GLib 2.22</li>
	<li>dbus-sharp 0.7</li>
	<li>dbus-sharp-glib 0.5</li>
	<li>Mono.Addins (mono-addins) 0.6.2</li>
	<li>TagLib# (taglib-sharp) &gt;= 2.0.3.7</li>
	<li>Required to build default feature stack:
<ul>
	<li>libmtp &gt;= 0.3.0</li>
	<li>mono-zeroconf &gt;= 0.8.0</li>
	<li>boo &gt;= 0.8.1</li>
	<li>webkit-1.0 &gt;= 1.2.2</li>
	<li>gdata-sharp-youtube &gt;= 1.4</li>
	<li>gio-sharp &gt;= 2.22.3, gtk-sharp-beans &gt;= 2.14.1, gudev-sharp and gkeyfile-sharp</li>
	<li>libgpod-sharp &gt;= 0.7.95</li>
	<li>Mono.Upnp &gt;= 0.1</li>
</ul>
</li>
	<li>Run-time requirements for default feature stack:
<ul>
	<li>udev</li>
	<li>media-player-info</li>
	<li>Brasero &gt;= 0.8.1</li>
	<li>Avahi</li>
	<li>gst-plugins-bad (providing the bpmdetect GStreamer plugin)</li>
</ul>
</li>
</ul>
<h3>Community</h3>
<a name="contributors"></a>
<h4>Contributors For This Release</h4>
The following people directly contributed to the release of this version of Banshee. Without their help, there would be no release!
<blockquote>
    $contributors
</blockquote>
The following people contributed updated translations to this release.    Without them, our project's reach would be much more limited.
<blockquote>
    $translators
</blockquote>
<h4>Contributors In Past Releases</h4>
<blockquote>
    
</blockquote>

<h4>Reporting Bugs, Joining the Community</h4>
If you encounter any bad behavior with this release, please do not hesitate to <a href="/contribute/file-bugs/">file bugs</a>!

We welcome new contributors - developers, translators, artists, writers, support gurus - to join our community.  <a href="/contribute">Join us!</a>
END

print $html;
